### PR TITLE
Add support for Rails' `annotate_rendered_view_with_filenames` option

### PR DESCRIPTION
**Pull request by oboxodo**
This is a raw first version that works. It's taken from https://translate.google.com/translate?sl=auto&tl=en&u=https://zenn.dev/kehra/articles/bbecaeb830032b which in turn adapts Rails' own code for Erb support.

I'm unfamiliar with Temple's code so I'd like some feedback and direction in case there's a better way to do this. Maybe a filter? Not sure. What would be the best way to add an automated test for this?

I've tested it in a real big Rails app using slim (which in turn uses temple) and it works perfectly.

### CODE REVIEW

**Comment by oboxodo** [comment]
@k0kubun @judofyr @minad sorry to ping you guys but do you think you could provide some feedback on this?

**Comment by k0kubun** [comment]
I think this should be generating Temple IRs (`[:static, "<!-- ... -->"]`) so that it could be merged with other static strings for performance. See how I implemented that at https://github.com/k0kubun/hamlit/commit/72bc1611f7df76397b58bad8ed0898ec449ec5fe.

**Comment by oboxodo** [comment]
Very interesting, @k0kubun. Is there anything in your implementation that makes it hamlit-specific? It looks to me that it could potentially be moved to template and then all view engines using temple could benefit from your implementation. Do you think that would be too difficult?

**Comment by k0kubun** [comment]
I filed https://github.com/judofyr/temple/pull/134. That should work. However, because it's just a copy-paste from my personal gem, I'd like another maintainer to take a look at the design before moving forward.

**Comment by oboxodo** [comment]
Thank you, @k0kubun!

I'm closing this PR in favor of yours (#134)

**Pull request closed without merging**
