### PR TITLE
[Bugfix] Use the specified capture_generator even for nested captures

### PR DESCRIPTION
**Pull request by jirutka**
We may get a capture nested inside another capture. For example Slim generates such Sexp for:

```slim
.foo class=@class
```

In this case three generators are initialized: the main generator G0, the capture_generator G1 created by G0 in `#on_capture`, the capture_generator G2 created by G1 in `#on_capture`.

The problem is that `Generator#on_capture` does not pass option `:capture_generator` into the generator being created. Thus G1 always uses the default capture_generator (`StringBuffer`), not the one originally specified by the option `:capture_generator`.

### CODE REVIEW

**Comment by jirutka** [comment]
@judofyr, it’s almost 3 years since I’ve opened this PR and still no response…

**Comment by jirutka** [comment]
The build failed only on Ruby 1.9.3 which is after its end of life for a very long time.

**Review by k0kubun — APPROVED** [review]

**Comment by timriley** [comment]
👋🏼 Hi folks (and cc @minad, as the author of [the commit](https://github.com/judofyr/temple/commit/181ea35a5d862af370f22adf0cb52663b9a151db) that rolled this PR back) —

I've just hit this issue myself. I'm [working on changes in hanai-view](https://github.com/hanami/view/pull/229/commits/80725926fa5327fd8b90ae946b14a1181c8ae7d6) that mark captured template content (made via Temple's `:capture` sexps) as `html_safe`.

I've done so via creating a custom capture generator:

```ruby
class HTMLSafeStringBuffer < Temple::Generators::StringBuffer
  def return_buffer
    byebug
    "#{buffer}.html_safe"
  end
end
```

And then specifying it as the default value for the `:capture_generator` option on my engine:

```ruby
module Hanami
  class View
    module ERB
      require_relative "parser"
      require_relative "filters/block"
      require_relative "filters/trimming"

      # Hanami::View ERB engine.
      #
      # @api private
      # @since 2.0.0
      class Engine < Temple::Engine
        define_options capture_generator: Hanami::View::HTMLSafeStringBuffer
```

However, when I create nested captures, e.g.

```erb
<%= some_capture_method do %>
  <div>Outer content</div>
  <%= some_capture_method do %>
    <div>Inner content</div>
  <% end %>
<% end %>
```

Then in this case, the `HTMLSafeStringBuffer` is used as the capture generator _only_ on the outer capture, not the inner capture.

This seems to be an identical scenario to what @jirutka described in the top-level description for this PR.

Is there a way we can solve this in Temple while still satisfying whatever requirements led to your rollback commit, @minad?

And in the meantime, @jirutka, I'm wondering if you might have something you can share about how you possibly worked around this issue in Slim or elsewhere?

Thank you!

**Comment by timriley** [comment]
To make my use case clearer, I've extracted it to a dedicated PR: https://github.com/hanami/view/pull/230

This PR has three commits:

1. ✅ The [first commit](https://github.com/hanami/view/pull/230/commits/f00f8d25e855e8c9e2a4b3d12da43090117305a7) introduces a custom `:capture_generator` to serve our specific needs for hanami-view. It includes tests to cover one level of depth for block capturing in templates. Test passes.
2. 🔴 The [second commit](https://github.com/hanami/view/pull/230/commits/3db62301c8dd64ed0bec46c74ab967988cfd77db) adds another test to cover nested block capturing in templates. The inner block is _not_ using the custom `:capture_generator` that we've specified on our Temple engine. Test fails.
3. ✅ The [final commit](https://github.com/hanami/view/pull/230/commits/b2f74c3563cd1c3191e94c06d60ee4fb7f7fcb70) locally patches Temple to match the change in this PR. This ensures the configured `:capture_generator` is used for all levels of nested block capturing. Test passes again!

So of the three changes that @minad rolled back in https://github.com/judofyr/temple/commit/181ea35a5d862af370f22adf0cb52663b9a151db, the only one that I'd love to see reintroduced (at least to cover our needs in hanami-view!) would be the change from this PR.

@minad — in your commit message you seem primarily concerned in making sure the main generator is separated from the capture generator. I can definitely understand how mixing the two could introduce regressions, but the specific change from this PR doesn't seem to mix the generators at all, instead just ensuring that options are appropriately propagated to newly created capture generators. So my thinking is that perhaps this PR is still safe to apply, and it possibly didn't need to be included in the reverts you made before?

I'd be happy to open another PR with the same diff as this one, if that would help! Thanks for checking this out ❤️

**Comment by minad** [comment]
@timriley The rolled back commit *introduced* a regression in Slim.  It wasn't only a concern. See https://github.com/slim-template/slim/issues/898.

**Comment by timriley** [comment]
Thanks for following this up, @minad!

The reason I'm following up here is because you rolled back three commits:

- Fix the default value of :capture_generator (https://github.com/judofyr/temple/commit/8e5c7a2c147ff31a4735d70bddd3f64425bcbae7)
- Use the specified capture_generator even for nested captures (https://github.com/judofyr/temple/pull/112, https://github.com/judofyr/temple/commit/a98bc35a951526471fff4d6b5aac8d8b2a7014af)
- Change default :capture_generator to self (https://github.com/judofyr/temple/commit/b0f1f6bdf8af8cbaa18f41d6cd080cc85cf27bb0)

The first commit and the last commit there are about setting the _value_ of `capture_generator`, while the middle commit (which is what I'm discussion here) is simply about propagating options when capture_generator is used.

So the middle commit is capture-related, yes, but it seems like it might not have been the particular source of the bug in slim, since it doesn't change the _value_ of the capture_generator at all.

So I think it makes complete sense to keep those other 2 commits reverted, I'm just following up about this middle one. It feels safe and IMHO it does fix a legitimate bug (see e.g. my PR). Does that clarify my position a little better?

I'll see if I can manually test this change against slim, but I thought it'd be worth trying to follow up here in writing first 😄

**Comment by minad** [comment]
@timriley I have to look in detail at this. The problem were nested captures in Rails, so it matters if something is propagated. I would need a small regression test which demonstrates https://github.com/slim-template/slim/issues/898 and then check these commits again for their exact effect. Capturing is the most problematic part of Temple because of the different handling in Rails/non-Rails.

**Comment by minad** [comment]
Thanks for your investigation and putting this together. This is greatly appreciated. Still, I have to insist on a regression test or additional tests, which reduce the risk that problematic changes regarding capturing make it into Temple or Slim in the future. The capturing code is clearly not tested well enough. I think we need at least a small regression test for the special scenario from https://github.com/slim-template/slim/issues/898 in Slim and then additional tests which check the modified behavior of the capture generator in Temple.

**Comment by timriley** [comment]
@minad I've just updated https://github.com/judofyr/temple/pull/144 with the changes to the test we discussed, and opened https://github.com/slim-template/slim/pull/917 with the regression test for Slim.

Let me know if there's anything more you'd like to see!

**Pull request merged**
