### PR TITLE
v0.7.7

### PR DESCRIPTION
**Pull request by gfortaine**
-Merge PR #95, #96, #98

-Reduce string allocations

https://github.com/schneems/temple/commit/15dd0ccfaed91e7579696254e326de
5a0569d36e

-remove unneeded case statement for erb parsing

https://github.com/kbrock/temple/commit/a488357f063e57dd090cfc1e316ecf7a
88b5a71c

### CODE REVIEW

**Comment by minad** [comment]
please don't squash the PRs

**Comment by minad** [comment]
It would be great if you could extract the other changes

**Comment by gfortaine** [comment]
Done (cf PR #100)

**Comment by minad** [comment]
cool thx

**Pull request closed without merging**
