### PR TITLE
Various optimizations

### PR DESCRIPTION
**Pull request by gfortaine**
-Reduce string allocations

https://github.com/schneems/temple/commit/15dd0ccfaed91e7579696254e326de
5a0569d36e

-remove unneeded case statement for erb parsing

https://github.com/kbrock/temple/commit/a488357f063e57dd090cfc1e316ecf7a
88b5a71c

### CODE REVIEW

**Comment by judofyr** [comment]
This this a bit dangerous?

After this commit:

```
>> a = "<hello>"
=> "<hello>"
>> Temple::Utils.escape_html(a)
=> "&lt;hello&gt;"
>> a
=> "&lt;hello&gt;"
```

**Comment by minad** [comment]
Thx. You are perfectly right. The mutation was the reason I didnt merge this originally.

We have to revert this one.

Am 20. Mai 2016 19:03:34 MESZ, schrieb Magnus Holm <notifications@github.com>:

**Comment by gfortaine** [comment]
I don't have this bug. My setup is ruby 2.4.0dev.

**Comment by minad** [comment]
The escape function is not allowed to mutate state - therefore I had to revert it.

**Comment by k0kubun** [comment]
> I don't have this bug. My setup is ruby 2.4.0dev.

Since the cgi/escape extension is introduced in Ruby 2.3 and https://github.com/judofyr/temple/pull/98 exists, the change for `Temple::Utils.escape_html` is applied to only Ruby 2.2 and lower. You can't check the mutation with Ruby 2.4.

**Pull request merged**
