### PR TITLE
Create Temple::Filters::StringSplitter

### PR DESCRIPTION
**Pull request by k0kubun**
Extract Hamlit::StringSplitter filter from [Hamlit](https://github.com/k0kubun/hamlit), which splits `:dynamic` with string interpolation into some `:dynamic` and `:static`.
You can utilize some optimizers for `:static` by this filter.

### CODE REVIEW

**Comment by minad** [comment]
@k0kubun I merged your filters. Sorry that I forgot about them. Should I release a new version such that you can use them in hamlit?

**Comment by k0kubun** [comment]
Thank you for merging. I'll use them if new version of temple is released. :)

**Comment by minad** [comment]
done!

**Comment by minad** [comment]
If you have other things you want to change or add, please let me know!

**Comment by k0kubun** [comment]
Thank you!

**Pull request merged**
